### PR TITLE
[Hito1][@pepitoenpeligro] Entrega Hito 1

### PR DESCRIPTION
**Pull request by pepitoenpeligro**
# Entrega del hito de Cloud Computing

Corresponde al hito 1

## Primero y más importante

* [x] Prometo no cerrar *nunca* un PR
* [x] ... ni eliminar mi repo si el PR va mal ...
* [x] ... ni abrir 2 PRs de lo mismo.

## Lista de comprobación para hitos

* [x] He leído el guión del hito
* [x] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
* [ ] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.

## Descripción de la entrega

Entrega hito 1

* [Milestone 1](https://github.com/pepitoenpeligro/CloudBanking/milestone/2)
  - [Technology feasibility study](https://github.com/pepitoenpeligro/CloudBanking/issues/9)
  - [Change Name from CC-Project to CloudBanking and re-describe problem to solve](https://github.com/pepitoenpeligro/CloudBanking/issues/10)
  - [Architecture description](https://github.com/pepitoenpeligro/CloudBanking/issues/11)
  - [Milestones and Issues description involved in this project](https://github.com/pepitoenpeligro/CloudBanking/issues/12)
  - [Create initial project structure in rust](https://github.com/pepitoenpeligro/CloudBanking/issues/31)
  - [Create basic structure](https://github.com/pepitoenpeligro/CloudBanking/issues/32)
  - [Create Entity descriptor (cc.yaml) enhancement](https://github.com/pepitoenpeligro/CloudBanking/issues/33)
* [User-Stories (HU)](https://github.com/pepitoenpeligro/CloudBanking/milestone/3)
  -  [(HU1) Add bank account as customer user user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/13)
  -  [(HU2) Add bank-card as customer user](https://github.com/pepitoenpeligro/CloudBanking/issues/14)
  -  [(HU3) Add investment fund as customer user](https://github.com/pepitoenpeligro/CloudBanking/issues/15)
  -  [(HU4) Delete bank account as customer user user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/16)
  -  [(HU5) Delete bank card as customer user user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/17)
  -  [(HU6) Delete fund investment as customer user user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/18)
  -  [(HU7) Create saving-group user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/19)
  -  [(HU8) Exit from saving-group user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/20)
  -  [(HU9) Create a payment-group user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/21)
  -  [(HU10) Exit from payment-group](https://github.com/pepitoenpeligro/CloudBanking/issues/22)
  -  [(HU11) Create alert-trigger for bank-account movement user-stories](https://github.com/pepitoenpeligro/CloudBanking/issues/23)
  -  [(HU12) Create alert-trigger for bank-card movement](https://github.com/pepitoenpeligro/CloudBanking/issues/24)
  -  [(HU13) Create alert-trigger for fund investment movement](https://github.com/pepitoenpeligro/CloudBanking/issues/25)
  -  [(HU14) Create account - register user](https://github.com/pepitoenpeligro/CloudBanking/issues/26)
  -  [(HU15) Loggin user](https://github.com/pepitoenpeligro/CloudBanking/issues/27)
  -  [(HU16) Erase Account](https://github.com/pepitoenpeligro/CloudBanking/issues/28)
  -  [(H17) Disable account](https://github.com/pepitoenpeligro/CloudBanking/issues/29)
  -  [(H18) Enable disabled account](https://github.com/pepitoenpeligro/CloudBanking/issues/30)

### CODE REVIEW

**Comment by JJ** [comment]
Resuelve los conflictos para fusionarla, por favor.

**Comment by pepitoenpeligro** [comment]
He actualizado el repo con los cambios de Arturo, y se ha cerrado el PR. Lo siento. Voy a subsanarlo

**Comment by pepitoenpeligro** [comment]
Y reabierto el PR, y parece que no existe ningún conflicto adicional. Quedo a disposición si hubiera algo raro más. Mil gracias!

**Comment by JJ** [comment]
> He actualizado el repo con los cambios de Arturo, y se ha cerrado el PR. Lo siento. Voy a subsanarlo

No, lo has actualizado sin ningún cambio, lo que os dije que no hiciérais.

**Pull request merged**
